- name: create tmp.mount
  become: 'yes'
  template:
    src: tmp.mount.j2
    dest: "{{ systemd_tmp_mount_path }}"
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - mount
    - systemd
    - tmp
    - CCE-82139-7
    - CCE-82140-5
    - CCE-82623-0

- name: stat tmp.mount
  stat:
    path: /etc/systemd/system/tmp.mount
  register: tmp_mount
  tags:
    - mount
    - tmp

- name: unmask tmp.mount
  become: 'yes'
  systemd:
    name: tmp.mount
    masked: 'no'
  when: tmp_mount.stat.exists
  tags:
    - mount
    - systemd
    - tmp

- name: start tmp.mount
  become: 'yes'
  systemd:
    name: tmp.mount
    daemon_reload: 'yes'
    state: started
    enabled: 'yes'
  when: tmp_mount.stat.exists
  tags:
    - mount
    - systemd
    - tmp
    